version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: "postgres:15.2"
    env_file:
      - ./.env
    restart: always
    ports:
      - "5432:5432"
    volumes:
    # Store the db data on the host machine, not inside the container.
    # Put a better path than /tmp!
      - /tmp/postgresql:/var/lib/postgresql
      - /tmp/postgresql/data:/var/lib/postgresql/data